### ISSUE TITLE
Dependencies from requirements.txt not being installed

### ISSUE THREAD

**Issue by fixmycode** [db0/pythorhead#49]
I had this experience with v0.9 from PyPI and v0.12.1 from github, I can't discard is not an issue with my environment.
I have pythorhead defined in my own requirements, no version filter for the PyPI package, and using the `@0.12.1'` label for the git package.

I'm running this on MacOS 12.6.7 and Python is running in a Conda environment

- Python 3.11.4
- pip 23.1.2
- setuptools 68.0.0

This is the output from installing from git:

```Collecting git+https://github.com/db0/pythorhead.git@v0.12.2 (from -r requirements.txt (line 2))
  Cloning https://github.com/db0/pythorhead.git (to revision v0.12.2) to /private/var/folders/nk/n1s318m55ng7hzp447rmzfp40000gn/T/pip-req-build-867ad0oi
  Running command git clone --filter=blob:none --quiet https://github.com/db0/pythorhead.git /private/var/folders/nk/n1s318m55ng7hzp447rmzfp40000gn/T/pip-req-build-867ad0oi
  Running command git checkout -q e813abb1372e4bc93dff483499b4c7385bb9453b
  Resolved https://github.com/db0/pythorhead.git to commit e813abb1372e4bc93dff483499b4c7385bb9453b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pythorhead
  Building wheel for pythorhead (pyproject.toml) ... done
  Created wheel for pythorhead: filename=pythorhead-0.12.1-py3-none-any.whl size=43580 sha256=33ce7e1cda86f0ba08b53153e9d477213fbb33b7247e7b755a81644337d26760
  Stored in directory: /private/var/folders/nk/n1s318m55ng7hzp447rmzfp40000gn/T/pip-ephem-wheel-cache-ubqgqoxi/wheels/cd/2b/ac/f1d913b8ee0b8a3d0bc3b0b3a2ba4b125ef0a7ea90c7af226a
Successfully built pythorhead
Installing collected packages: pythorhead
Successfully installed pythorhead-0.12.1
```

After this, the `requests` package is not installed

```pip freeze
pythorhead @ git+https://github.com/db0/pythorhead.git@e813abb1372e4bc93dff483499b4c7385bb9453b
pytz==2023.3
six==1.16.0
typing_extensions==4.7.1
tzlocal==5.0.1
```

And any request fails from this:

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/oni/miniforge3/envs/my_env/lib/python3.11/site-packages/pythorhead/__init__.py", line 1, in <module>
    from pythorhead.lemmy import Lemmy
  File "/Users/oni/miniforge3/envs/my_env/lib/python3.11/site-packages/pythorhead/lemmy.py", line 4, in <module>
    from pythorhead.comment import Comment
  File "/Users/oni/miniforge3/envs/my_env/lib/python3.11/site-packages/pythorhead/comment.py", line 3, in <module>
    from pythorhead.requestor import Request, Requestor
  File "/Users/oni/miniforge3/envs/my_env/lib/python3.11/site-packages/pythorhead/requestor.py", line 5, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by chalbersma** [comment]
For the dependencies I think a dependencies stanza needs to be added to the `.toml` file to make a dependency install.

```
dependencies = [
    "requests",
    "someotherdep",
   ...
]

**Comment by fixmycode** [comment]
From what I read, this should be sufficient:

https://github.com/db0/pythorhead/blob/main/pyproject.toml#L28-L29

Wondering why is not picking it up
